// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Database struct {
	CompartmentID  string `json:"compartmentId"`
	DbHomeID       string `json:"dbHomeId"`
	DbName         string `json:"dbName"`
	DbUniqueName   string `json:"dbUniqueName"`
	CharacterSet   string `json:"characterSet"`
	NcharacterSet  string `json:"ncharacterSet"`
	ID             string `json:"id"`
	KmsKeyID       string `json:"kmsKeyId"`
	LifecycleState string `json:"lifecycleState"`
	TimeCreated    string `json:"timeCreated"`
	AdminPassword  string `json:"adminPassword"`
}

type NewDatabase struct {
	DbName        string `json:"dbName"`
	AdminPassword string `json:"adminPassword"`
}
